# PQC Scheduler - NTT Accelerator Synthesis Script for Vivado
# Copyright (c) 2025 Dyber, Inc. All Rights Reserved.
#
# Usage: vivado -mode batch -source scripts/synth_ntt.tcl \
#              -tclargs <part> <frequency>
#
# Example: vivado -mode batch -source scripts/synth_ntt.tcl \
#                -tclargs xcu280-fsvh2892-2L-e 250MHz

# Parse arguments
if {$argc < 2} {
    puts "Usage: vivado -mode batch -source synth_ntt.tcl -tclargs <part> <frequency>"
    puts "  part:      Target FPGA part (e.g., xcu280-fsvh2892-2L-e)"
    puts "  frequency: Target frequency (e.g., 250MHz)"
    exit 1
}

set PART [lindex $argv 0]
set FREQ [lindex $argv 1]

# Extract frequency value
regexp {(\d+)} $FREQ -> FREQ_MHZ
set PERIOD_NS [expr {1000.0 / $FREQ_MHZ}]

puts "========================================"
puts "PQC Scheduler NTT Accelerator Synthesis"
puts "========================================"
puts "Part:      $PART"
puts "Frequency: $FREQ_MHZ MHz"
puts "Period:    $PERIOD_NS ns"
puts ""

# Project settings
set PROJECT_NAME "pqc_ntt_accel"
set PROJECT_DIR "./vivado_project"
set RTL_DIR "./rtl"
set CONSTRAINT_DIR "./constraints"
set OUTPUT_DIR "./bitstreams"

# Create output directories
file mkdir $PROJECT_DIR
file mkdir $OUTPUT_DIR

# Create project
create_project $PROJECT_NAME $PROJECT_DIR -part $PART -force

# Set project properties
set_property target_language Verilog [current_project]
set_property default_lib work [current_project]
set_property simulator_language Mixed [current_project]

# Add RTL source files
puts "Adding RTL sources..."

# NTT Engine Core
add_files -norecurse [list \
    "$RTL_DIR/ntt/ntt_top.v" \
    "$RTL_DIR/ntt/butterfly_radix16.v" \
    "$RTL_DIR/ntt/twiddle_rom.v" \
    "$RTL_DIR/ntt/modular_mult.v" \
    "$RTL_DIR/ntt/modular_add.v" \
    "$RTL_DIR/ntt/coefficient_mem.v" \
    "$RTL_DIR/ntt/ntt_controller.v" \
]

# ML-KEM Core
add_files -norecurse [list \
    "$RTL_DIR/mlkem/mlkem_top.v" \
    "$RTL_DIR/mlkem/polynomial_mult.v" \
    "$RTL_DIR/mlkem/polynomial_add.v" \
    "$RTL_DIR/mlkem/sampler_cbd.v" \
    "$RTL_DIR/mlkem/compress.v" \
    "$RTL_DIR/mlkem/decompress.v" \
    "$RTL_DIR/mlkem/encode.v" \
    "$RTL_DIR/mlkem/decode.v" \
]

# ML-DSA Core (signature)
add_files -norecurse [list \
    "$RTL_DIR/mldsa/mldsa_top.v" \
    "$RTL_DIR/mldsa/matrix_mult.v" \
    "$RTL_DIR/mldsa/highbits.v" \
    "$RTL_DIR/mldsa/lowbits.v" \
    "$RTL_DIR/mldsa/hint_compute.v" \
]

# Common modules
add_files -norecurse [list \
    "$RTL_DIR/common/sha3_core.v" \
    "$RTL_DIR/common/shake128.v" \
    "$RTL_DIR/common/shake256.v" \
    "$RTL_DIR/common/axi_stream_if.v" \
    "$RTL_DIR/common/fifo_sync.v" \
    "$RTL_DIR/common/fifo_async.v" \
]

# PCIe/DMA interface
add_files -norecurse [list \
    "$RTL_DIR/pcie/pcie_endpoint.v" \
    "$RTL_DIR/pcie/dma_engine.v" \
    "$RTL_DIR/pcie/command_parser.v" \
    "$RTL_DIR/pcie/completion_gen.v" \
]

# Top-level wrapper
add_files -norecurse "$RTL_DIR/pqc_accel_top.v"

# Add constraint files
puts "Adding constraints..."
add_files -fileset constrs_1 -norecurse [list \
    "$CONSTRAINT_DIR/timing.xdc" \
    "$CONSTRAINT_DIR/pinout_u280.xdc" \
    "$CONSTRAINT_DIR/floorplan.xdc" \
]

# Create timing constraint file if not exists
if {![file exists "$CONSTRAINT_DIR/timing.xdc"]} {
    file mkdir $CONSTRAINT_DIR
    set fp [open "$CONSTRAINT_DIR/timing.xdc" w]
    puts $fp "# PQC Accelerator Timing Constraints"
    puts $fp "# Auto-generated by synth_ntt.tcl"
    puts $fp ""
    puts $fp "# Primary clock"
    puts $fp "create_clock -period $PERIOD_NS -name clk_sys \[get_ports clk_sys\]"
    puts $fp ""
    puts $fp "# PCIe reference clock (100 MHz)"
    puts $fp "create_clock -period 10.000 -name pcie_refclk \[get_ports pcie_refclk_p\]"
    puts $fp ""
    puts $fp "# Clock groups"
    puts $fp "set_clock_groups -asynchronous \\"
    puts $fp "    -group \[get_clocks clk_sys\] \\"
    puts $fp "    -group \[get_clocks pcie_refclk\]"
    puts $fp ""
    puts $fp "# Input/output delays"
    puts $fp "set_input_delay -clock clk_sys -max 2.0 \[get_ports -filter {DIRECTION == IN}\]"
    puts $fp "set_output_delay -clock clk_sys -max 2.0 \[get_ports -filter {DIRECTION == OUT}\]"
    puts $fp ""
    puts $fp "# False paths for reset"
    puts $fp "set_false_path -from \[get_ports rst_n\]"
    close $fp
}

# Update compile order
update_compile_order -fileset sources_1

# Run synthesis
puts ""
puts "========================================"
puts "Running Synthesis"
puts "========================================"

# Synthesis settings for high performance
set_property strategy Flow_PerfOptimized_high [get_runs synth_1]
set_property STEPS.SYNTH_DESIGN.ARGS.RETIMING true [get_runs synth_1]
set_property STEPS.SYNTH_DESIGN.ARGS.FLATTEN_HIERARCHY rebuilt [get_runs synth_1]

launch_runs synth_1 -jobs [expr {min(8, [exec nproc])}]
wait_on_run synth_1

# Check synthesis status
if {[get_property PROGRESS [get_runs synth_1]] != "100%"} {
    puts "ERROR: Synthesis failed"
    exit 1
}

# Open synthesized design
open_run synth_1

# Report synthesis results
puts ""
puts "========================================"
puts "Synthesis Reports"
puts "========================================"

report_utilization -file "$OUTPUT_DIR/synth_utilization.rpt"
report_timing_summary -file "$OUTPUT_DIR/synth_timing.rpt"
report_power -file "$OUTPUT_DIR/synth_power.rpt"

# Print summary
puts ""
puts "Resource Utilization Summary:"
puts [report_utilization -return_string -hierarchical -hierarchical_depth 1]

# Run implementation
puts ""
puts "========================================"
puts "Running Implementation"
puts "========================================"

# Implementation settings
set_property strategy Performance_ExploreWithRemap [get_runs impl_1]
set_property STEPS.PLACE_DESIGN.ARGS.DIRECTIVE ExtraNetDelay_high [get_runs impl_1]
set_property STEPS.PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]
set_property STEPS.ROUTE_DESIGN.ARGS.DIRECTIVE AggressiveExplore [get_runs impl_1]
set_property STEPS.POST_ROUTE_PHYS_OPT_DESIGN.IS_ENABLED true [get_runs impl_1]

launch_runs impl_1 -jobs [expr {min(8, [exec nproc])}]
wait_on_run impl_1

# Check implementation status
if {[get_property PROGRESS [get_runs impl_1]] != "100%"} {
    puts "ERROR: Implementation failed"
    exit 1
}

# Generate bitstream
puts ""
puts "========================================"
puts "Generating Bitstream"
puts "========================================"

launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1

# Open implemented design
open_run impl_1

# Generate reports
report_utilization -file "$OUTPUT_DIR/impl_utilization.rpt"
report_timing_summary -file "$OUTPUT_DIR/impl_timing.rpt"
report_power -file "$OUTPUT_DIR/impl_power.rpt"
report_route_status -file "$OUTPUT_DIR/route_status.rpt"

# Copy bitstream
set BITSTREAM_NAME "mlkem768_ntt_${FREQ_MHZ}mhz"
file copy -force "$PROJECT_DIR/$PROJECT_NAME.runs/impl_1/pqc_accel_top.bit" "$OUTPUT_DIR/${BITSTREAM_NAME}.bit"
file copy -force "$PROJECT_DIR/$PROJECT_NAME.runs/impl_1/pqc_accel_top.ltx" "$OUTPUT_DIR/${BITSTREAM_NAME}.ltx" 

# Final timing check
puts ""
puts "========================================"
puts "Final Timing Analysis"
puts "========================================"

set WNS [get_property STATS.WNS [get_runs impl_1]]
set TNS [get_property STATS.TNS [get_runs impl_1]]

puts "Worst Negative Slack (WNS): $WNS ns"
puts "Total Negative Slack (TNS): $TNS ns"

if {$WNS < 0} {
    puts ""
    puts "WARNING: Timing not met! Consider reducing target frequency."
    puts "Current target: $FREQ_MHZ MHz ($PERIOD_NS ns period)"
    set ACHIEVED_FREQ [expr {1000.0 / ($PERIOD_NS - $WNS)}]
    puts "Achievable frequency: [format %.1f $ACHIEVED_FREQ] MHz"
}

puts ""
puts "========================================"
puts "Synthesis Complete"
puts "========================================"
puts "Bitstream: $OUTPUT_DIR/${BITSTREAM_NAME}.bit"
puts ""

# Close project
close_project

exit 0
